### ISSUE TITLE
issue：pip install -v -e . 

### ISSUE THREAD

**Issue by QY1994-0919** [JialeCao001/D2Det#30]
Hello, thank you very much for your reply to the previous question, but I still get an error while compiling with pip install -v -e .
I have performed the following two installation steps, but each has the same problem:
method one:
1.conda create -n mmd1 Python=3.6
2.conda activate mmd1
3.conda install pytorch==1.1.0 torchvision==0.3.0 cudatoolkit=10.0 -c pytorch
4.pip install mmcv==0.4.3
5.pycocotools
   cd /home/10102010/qy/detectron2_ubuntu/cocoapi-master/PythonAPI
   python setup.py build_ext install
6.cd /home/10102010/qy/Projects_qy/D2Det-master
pip install -r requirements/build.txt
pip install -v -e . or python setup.py develop

Method Two:
1.conda create -n mmd Python=3.6
2.conda activate mmd
3.conda install pytorch==1.1.0 torchvision==0.3.0 cudatoolkit=9.0 -c pytorch
4.pip install mmcv==0.4.3
5. Install pycocotools
   cd /home/10102010/qy/detectron2_ubuntu/cocoapi-master/PythonAPI
   python setup.py build_ext install
6.cd /home/10102010/qy/Projects_qy/D2Det-master directory
pip install -r requirements/build.txt
pip install -v -e . or python setup.py develop

issue:
 Running command python setup.py egg_info
    which: no nvcc in (/home/10102010/qy/mm2.3envir/anaconda3/cd../envs/mmd/bin:/cm/shared/apps/gcc5/5.5.0/bin:/cm/shared/apps/slurm/current/sbodules/4.4.0//bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/usr/sbin:/cm/local/apps/environment-modules/4.4.0/bin:/home/10102010
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/10102010/qy/Projects_qy/D2Det-master/setup.py", line 228, in <module>
        sources=['src/compiling_info.cpp']),
      File "/home/10102010/qy/Projects_qy/D2Det-master/setup.py", line 97, in make_cuda_ext
        raise EnvironmentError('CUDA is required to compile MMDetection!')
    OSError: CUDA is required to compile MMDetection!
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
Exception information:
Traceback (most recent call last):
  File "/home/10102010/qy/mm2.3envir/anaconda3/cd../envs/mmd/lib/python3.6/site-packages/pip/_internal/cli/base_command.py", line 228, in _main
    status = self.run(options, args)
  File "/home/10102010/qy/mm2.3envir/anaconda3/cd../envs/mmd/lib/python3.6/site-packages/pip/_internal/cli/req_command.py", line 182, in wrappe
    return func(self, options, args)
  File "/home/10102010/qy/mm2.3envir/anaconda3/cd../envs/mmd/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 324, in run
    reqs, check_supported_wheels=not options.target_dir
  File "/home/10102010/qy/mm2.3envir/anaconda3/cd../envs/mmd/lib/python3.6/site-packages/pip/_internal/resolution/legacy/resolver.py", line 183
    discovered_reqs.extend(self._resolve_one(requirement_set, req))
  File "/home/10102010/qy/mm2.3envir/anaconda3/cd../envs/mmd/lib/python3.6/site-packages/pip/_internal/resolution/legacy/resolver.py", line 388
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/home/10102010/qy/mm2.3envir/anaconda3/cd../envs/mmd/lib/python3.6/site-packages/pip/_internal/resolution/legacy/resolver.py", line 326
    return self.preparer.prepare_editable_requirement(req)
  File "/home/10102010/qy/mm2.3envir/anaconda3/cd../envs/mmd/lib/python3.6/site-packages/pip/_internal/operations/prepare.py", line 526, in pre
    req, self.req_tracker, self.finder, self.build_isolation,
  File "/home/10102010/qy/mm2.3envir/anaconda3/cd../envs/mmd/lib/python3.6/site-packages/pip/_internal/operations/prepare.py", line 91, in _get
    abstract_dist.prepare_distribution_metadata(finder, build_isolation)
  File "/home/10102010/qy/mm2.3envir/anaconda3/cd../envs/mmd/lib/python3.6/site-packages/pip/_internal/distributions/sdist.py", line 40, in pre
    self.req.prepare_metadata()
  File "/home/10102010/qy/mm2.3envir/anaconda3/cd../envs/mmd/lib/python3.6/site-packages/pip/_internal/req/req_install.py", line 555, in prepar
    self.metadata_directory = self._generate_metadata()
  File "/home/10102010/qy/mm2.3envir/anaconda3/cd../envs/mmd/lib/python3.6/site-packages/pip/_internal/req/req_install.py", line 535, in _gener
    details=self.name or "from {}".format(self.link)
  File "/home/10102010/qy/mm2.3envir/anaconda3/cd../envs/mmd/lib/python3.6/site-packages/pip/_internal/operations/build/metadata_legacy.py", li
    command_desc='python setup.py egg_info',
  File "/home/10102010/qy/mm2.3envir/anaconda3/cd../envs/mmd/lib/python3.6/site-packages/pip/_internal/utils/subprocess.py", line 242, in call_
    raise InstallationError(exc_msg)
pip._internal.exceptions.InstallationError: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command ou
Removed file:///home/10102010/qy/Projects_qy/D2Det-master from build tracker '/tmp/pip-req-tracker-0ujmvsq_'
Removed build tracker: '/tmp/pip-req-tracker-0ujmvsq_'

**Comment by JialeCao001** [comment]
@QY1994-0919 Hi. In fact, I cannot give you an accurate reason about this. "OSError: CUDA is required to compile MMDetection!" From this message, donot you install CUDA?

**Comment by QY1994-0919** [comment]
thank you very much ! 
I directly download your D2Det project, create a virtual environment under conda, and finally compile the project, and find that there is no mmdet file through conda list

**Comment by QY1994-0919** [comment]
Hello！
because I am a beginner and I am more interested in your work. I especially want to clarify your work, so if you take the liberty to ask, you can add your WeChat to make it easier to ask you

Thank you！













在 2020-11-19 11:22:48，"Jiale Cao" <notifications@github.com> 写道：

@QY1994-0919 Hi. In fact, I cannot give you an accurate reason about this. "OSError: CUDA is required to compile MMDetection!" From this message, donot you install CUDA?

**Comment by JialeCao001** [comment]
@Y1994-0919 I am okay. You can search my phone 15122502780

**Comment by ghost** [comment]
so have you ever reproduced D2Det and gotten the results in the paper?
