### ISSUE TITLE
ImportError: cannot import name 'corner_pool_ext'

### ISSUE THREAD

**Issue by QY1994-0919** [JialeCao001/D2Det#32]
Hello, I got the following error while training D2Det v2.1

Traceback (most recent call last):
  File "/home/10102010/qy/ubuntu_mmd2.3/D2Det-mmdet2.1-master/tools/train.py", line 13, in <module>
  File "/home/10102010/qy/ubuntu_mmd2.3/D2Det-mmdet2.1-master/tools/train.py", line 13, in <module>
    from mmdet.apis import set_random_seed, train_detector
    from mmdet.apis import set_random_seed, train_detector
  File "/home/10102010/qy/ubuntu_mmd2.3/D2Det-mmdet2.1-master/mmdet/apis/__init__.py", line 1, in <module>
  File "/home/10102010/qy/ubuntu_mmd2.3/D2Det-mmdet2.1-master/mmdet/apis/__init__.py", line 1, in <module>
    from .inference import (async_inference_detector, inference_detector,
    from .inference import (async_inference_detector, inference_detector,
  File "/home/10102010/qy/ubuntu_mmd2.3/D2Det-mmdet2.1-master/mmdet/apis/inference.py", line 9, in <module>
  File "/home/10102010/qy/ubuntu_mmd2.3/D2Det-mmdet2.1-master/mmdet/apis/inference.py", line 9, in <module>
    from mmdet.core import get_classes
    from mmdet.core import get_classes
  File "/home/10102010/qy/ubuntu_mmd2.3/D2Det-mmdet2.1-master/mmdet/core/__init__.py", line 2, in <module>
  File "/home/10102010/qy/ubuntu_mmd2.3/D2Det-mmdet2.1-master/mmdet/core/__init__.py", line 2, in <module>
    from .bbox import *  # noqa: F401, F403
    from .bbox import *  # noqa: F401, F403
  File "/home/10102010/qy/ubuntu_mmd2.3/D2Det-mmdet2.1-master/mmdet/core/bbox/__init__.py", line 7, in <module>
  File "/home/10102010/qy/ubuntu_mmd2.3/D2Det-mmdet2.1-master/mmdet/core/bbox/__init__.py", line 7, in <module>
    from .samplers import (BaseSampler, CombinedSampler,
    from .samplers import (BaseSampler, CombinedSampler,
  File "/home/10102010/qy/ubuntu_mmd2.3/D2Det-mmdet2.1-master/mmdet/core/bbox/samplers/__init__.py", line 9, in <module>
  File "/home/10102010/qy/ubuntu_mmd2.3/D2Det-mmdet2.1-master/mmdet/core/bbox/samplers/__init__.py", line 9, in <module>
    from .score_hlr_sampler import ScoreHLRSampler
    from .score_hlr_sampler import ScoreHLRSampler
  File "/home/10102010/qy/ubuntu_mmd2.3/D2Det-mmdet2.1-master/mmdet/core/bbox/samplers/score_hlr_sampler.py", line 3, in <module>
  File "/home/10102010/qy/ubuntu_mmd2.3/D2Det-mmdet2.1-master/mmdet/core/bbox/samplers/score_hlr_sampler.py", line 3, in <module>
    from mmdet.ops import nms_match
    from mmdet.ops import nms_match
  File "/home/10102010/qy/ubuntu_mmd2.3/D2Det-mmdet2.1-master/mmdet/ops/__init__.py", line 3, in <module>
  File "/home/10102010/qy/ubuntu_mmd2.3/D2Det-mmdet2.1-master/mmdet/ops/__init__.py", line 3, in <module>
    from .corner_pool import CornerPool
    from .corner_pool import CornerPool
  File "/home/10102010/qy/ubuntu_mmd2.3/D2Det-mmdet2.1-master/mmdet/ops/corner_pool/__init__.py", line 1, in <module>
  File "/home/10102010/qy/ubuntu_mmd2.3/D2Det-mmdet2.1-master/mmdet/ops/corner_pool/__init__.py", line 1, in <module>
    from . import corner_pool
    from . import corner_pool
  File "/home/10102010/qy/ubuntu_mmd2.3/D2Det-mmdet2.1-master/mmdet/ops/corner_pool/corner_pool.py", line 4, in <module>
  File "/home/10102010/qy/ubuntu_mmd2.3/D2Det-mmdet2.1-master/mmdet/ops/corner_pool/corner_pool.py", line 4, in <module>
    from . import corner_pool_ext
    from . import corner_pool_ext
ImportError: cannot import name 'corner_pool_ext'
ImportError: cannot import name 'corner_pool_ext'
Traceback (most recent call last):
  File "/home/10102010/qy/mm2.3envir/anaconda3/cd../envs/mmd21/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/10102010/qy/mm2.3envir/anaconda3/cd../envs/mmd21/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/10102010/qy/mm2.3envir/anaconda3/cd../envs/mmd21/lib/python3.6/site-packages/torch/distributed/launch.py", line 263, in <module>
    main()
  File "/home/10102010/qy/mm2.3envir/anaconda3/cd../envs/mmd21/lib/python3.6/site-packages/torch/distributed/launch.py", line 259, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/10102010/qy/mm2.3envir/anaconda3/cd../envs/mmd21/bin/python', '-u', '/home/10102010/qy/ubuntu_mmd2.3/D2Det-mmdet2.1-master/tools/train.py', '--local_rank=1', '/home/10102010/qy/ubuntu_mmd2.3/D2Det-mmdet2.1-master/configs/d2det/D2Det_detection_r50_fpn_2x.py', '--launcher', 'pytorch', '--work-dir']' returned non-zero exit status 1.
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************

**Comment by GgShine** [comment]
您好，请问下您目前在研究d2det嘛
